//! Token types and definitions. Generated by CongoCC Parser Generator. Do not edit.

use std::fmt;

/// Token type enumeration
///
/// Represents all possible token types recognized by the lexer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[allow(non_camel_case_types)]
pub enum TokenType {
    /// Token: EOF
        EOF,
    /// Token: _TOKEN_1
        Token1,
    /// Token: _TOKEN_2
        Token2,
    /// Token: _TOKEN_3
        Token3,
    /// Token: _TOKEN_4
        Token4,
    /// Token: _TOKEN_5
        Token5,
    /// Token: NOT
        NOT,
    /// Token: AND
        AND,
    /// Token: OR
        OR,
    /// Token: BETWEEN
        BETWEEN,
    /// Token: LIKE
        LIKE,
    /// Token: ESCAPE
        ESCAPE,
    /// Token: IN
        IN,
    /// Token: IS
        IS,
    /// Token: TRUE
        TRUE,
    /// Token: FALSE
        FALSE,
    /// Token: NULL
        NULL,
    /// Token: _TOKEN_17
        Token17,
    /// Token: _TOKEN_18
        Token18,
    /// Token: _TOKEN_19
        Token19,
    /// Token: _TOKEN_20
        Token20,
    /// Token: _TOKEN_21
        Token21,
    /// Token: _TOKEN_22
        Token22,
    /// Token: _TOKEN_23
        Token23,
    /// Token: _TOKEN_24
        Token24,
    /// Token: _TOKEN_25
        Token25,
    /// Token: _TOKEN_26
        Token26,
    /// Token: _TOKEN_27
        Token27,
    /// Token: _TOKEN_28
        Token28,
    /// Token: _TOKEN_29
        Token29,
    /// Token: _TOKEN_30
        Token30,
    /// Token: LINE_COMMENT
        LINE_COMMENT,
    /// Token: BLOCK_COMMENT
        BLOCK_COMMENT,
    /// Token: DECIMAL_LITERAL
        DECIMAL_LITERAL,
    /// Token: HEX_LITERAL
        HEX_LITERAL,
    /// Token: OCTAL_LITERAL
        OCTAL_LITERAL,
    /// Token: FLOATING_POINT_LITERAL
        FLOATING_POINT_LITERAL,
    /// Token: STRING_LITERAL
        STRING_LITERAL,
    /// Token: ID
        ID,
    /// Invalid token marker
    INVALID,
}

impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenType::EOF => write!(f, "EOF"),
            TokenType::Token1 => write!(f, "_TOKEN_1"),
            TokenType::Token2 => write!(f, "_TOKEN_2"),
            TokenType::Token3 => write!(f, "_TOKEN_3"),
            TokenType::Token4 => write!(f, "_TOKEN_4"),
            TokenType::Token5 => write!(f, "_TOKEN_5"),
            TokenType::NOT => write!(f, "NOT"),
            TokenType::AND => write!(f, "AND"),
            TokenType::OR => write!(f, "OR"),
            TokenType::BETWEEN => write!(f, "BETWEEN"),
            TokenType::LIKE => write!(f, "LIKE"),
            TokenType::ESCAPE => write!(f, "ESCAPE"),
            TokenType::IN => write!(f, "IN"),
            TokenType::IS => write!(f, "IS"),
            TokenType::TRUE => write!(f, "TRUE"),
            TokenType::FALSE => write!(f, "FALSE"),
            TokenType::NULL => write!(f, "NULL"),
            TokenType::Token17 => write!(f, "_TOKEN_17"),
            TokenType::Token18 => write!(f, "_TOKEN_18"),
            TokenType::Token19 => write!(f, "_TOKEN_19"),
            TokenType::Token20 => write!(f, "_TOKEN_20"),
            TokenType::Token21 => write!(f, "_TOKEN_21"),
            TokenType::Token22 => write!(f, "_TOKEN_22"),
            TokenType::Token23 => write!(f, "_TOKEN_23"),
            TokenType::Token24 => write!(f, "_TOKEN_24"),
            TokenType::Token25 => write!(f, "_TOKEN_25"),
            TokenType::Token26 => write!(f, "_TOKEN_26"),
            TokenType::Token27 => write!(f, "_TOKEN_27"),
            TokenType::Token28 => write!(f, "_TOKEN_28"),
            TokenType::Token29 => write!(f, "_TOKEN_29"),
            TokenType::Token30 => write!(f, "_TOKEN_30"),
            TokenType::LINE_COMMENT => write!(f, "LINE_COMMENT"),
            TokenType::BLOCK_COMMENT => write!(f, "BLOCK_COMMENT"),
            TokenType::DECIMAL_LITERAL => write!(f, "DECIMAL_LITERAL"),
            TokenType::HEX_LITERAL => write!(f, "HEX_LITERAL"),
            TokenType::OCTAL_LITERAL => write!(f, "OCTAL_LITERAL"),
            TokenType::FLOATING_POINT_LITERAL => write!(f, "FLOATING_POINT_LITERAL"),
            TokenType::STRING_LITERAL => write!(f, "STRING_LITERAL"),
            TokenType::ID => write!(f, "ID"),
            TokenType::INVALID => write!(f, "INVALID"),
        }
    }
}

/// Lexical state enumeration
///
/// Represents different lexical states the lexer can be in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum LexicalState {
    /// Lexical state: DEFAULT
    DEFAULT,
}

/// A single token in the input stream
///
/// Tokens are the atomic units produced by the lexer. Each token has:
/// - A type (e.g., INTEGER, PLUS, EOF)
/// - An image (the actual text matched)
/// - Position information (begin/end offsets)
/// - Optional links to previous/next tokens
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Token {
    /// The type of this token
    pub token_type: TokenType,
    /// The actual text of this token
    pub image: String,
    /// Absolute offset in the input where this token begins
    pub begin_offset: usize,
    /// Absolute offset in the input where this token ends
    pub end_offset: usize,
    /// Index of the next token (if any)
    pub next: Option<usize>,
    /// Index of the previous token (if any)
    pub previous: Option<usize>,
}

impl Token {
    /// Create a new token
    pub fn new(
        token_type: TokenType,
        image: String,
        begin_offset: usize,
        end_offset: usize,
    ) -> Self {
        Token {
            token_type,
            image,
            begin_offset,
            end_offset,
            next: None,
            previous: None,
        }
    }

    /// Get the length of this token in characters
    pub fn len(&self) -> usize {
        self.end_offset.saturating_sub(self.begin_offset)
    }

    /// Check if this token is empty
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Check if this token is of a specific type
    pub fn is_type(&self, token_type: TokenType) -> bool {
        self.token_type == token_type
    }

    /// Check if this token is one of the specified types
    pub fn is_one_of(&self, types: &[TokenType]) -> bool {
        types.contains(&self.token_type)
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: \"{}\"", self.token_type, self.image)
    }
}

/// Token source trait for tracking token locations
pub trait TokenSource {
    /// Get the line number for a given offset
    fn get_line_from_offset(&self, offset: usize) -> usize;

    /// Get the column number for a given offset
    fn get_column_from_offset(&self, offset: usize) -> usize;
}
